line-height = 1.3

[colors]
background = "#100F0F"
foreground = "#CECDC3"

# Cursor
cursor = "#CECDC3"

# Selection
selection-foreground = "#CECDC3"
selection-background = "#282726"

# Search
search-match-foreground = "#CECDC3"
search-match-background = "#343331"
search-focused-match-foreground = "#100F0F"
search-focused-match-background = "#87D3C3"

# Hints
hint-foreground = "#100F0F"
hint-background = "#D0A215"

# Navigation / bar
bar = "#1C1B1A"
tabs = "#CECDC3"
tabs-active = "#CECDC3"

# Regular colors
black = "#100F0F"
red = "#D14D41"
green = "#879A39"
yellow = "#D0A215"
blue = "#4385BE"
magenta = "#CE5D97"
cyan = "#3AA99F"
white = "#FFFCF0"

# Dim colors
dim-black = "#100F0F"
dim-red = "#AF3029"
dim-green = "#66800B"
dim-yellow = "#AD8301"
dim-blue = "#205EA6"
dim-magenta = "#A02F6F"
dim-cyan = "#24837B"
dim-white = "#CECDC3"
dim-foreground = "#6F6E68"

# Bright colors
light-black = "#878580"
light-red = "#F89A8A"
light-green = "#BEC97E"
light-yellow = "#ECCB60"
light-blue = "#92BFDB"
light-magenta = "#F4A4C2"
light-cyan = "#87D3C3"
light-white = "#FFFCF0"
light-foreground = "#CECDC3"

[cursor]
shape = "beam"
blinking = false

[fonts]
size = 12
regular = { family = "Berkeley Mono", style = "Normal" }


[shell]
program = "/opt/homebrew/bin/nu"
args = ["--config", "~/.config.nu", "--env-config", "~/.env.nu"]

[window]
mode = "Maximized"

[navigation]
mode = "NativeTab"
unfocused-split-opacity = 0.4

[panel]
column-gap = 15
