[colors.primary]
background = "#100F0F"
foreground = "#CECDC3"
dim_foreground = "#6F6E68"
bright_foreground = "#CECDC3"

[colors.cursor]
text = "#100F0F"
cursor = "#CECDC3"

[colors.selection]
text = "#CECDC3"
background = "#282726"

[colors.search.matches]
foreground = "#CECDC3"
background = "#343331"

[colors.search.focused_match]
foreground = "#100F0F"
background = "#87D3C3"

[colors.hints.start]
foreground = "#100F0F"
background = "#D0A215"

[colors.hints.end]
foreground = "#CECDC3"
background = "#1C1B1A"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#CECDC3"
background = "#1C1B1A"

[colors.normal]
black   = "#100F0F"
red     = "#D14D41"
green   = "#879A39"
yellow  = "#D0A215"
blue    = "#4385BE"
magenta = "#CE5D97"
cyan    = "#3AA99F"
white   = "#FFFCF0"

[colors.bright]
black   = "#878580"
red     = "#F89A8A"
green   = "#BEC97E"
yellow  = "#ECCB60"
blue    = "#92BFDB"
magenta = "#F4A4C2"
cyan    = "#87D3C3"
white   = "#FFFCF0"

[colors.dim]
black   = "#100F0F"
red     = "#AF3029"
green   = "#66800B"
yellow  = "#AD8301"
blue    = "#205EA6"
magenta = "#A02F6F"
cyan    = "#24837B"
white   = "#CECDC3"

[cursor]
vi_mode_style = "Block"
style = {shape = "Beam", blinking = "Off"}

[font]
size = 12
normal = { family = "Berkeley Mono", style = "Regular" }
offset = { x = 0, y = 5 }

[terminal]
shell = { program = "/opt/homebrew/bin/nu", args = ["--config", "~/.config.nu", "--env-config", "~/.env.nu"]}

[window]
startup_mode = "Maximized"
