[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
gofumpt = true
staticcheck = true

[language-server.gleam]
command = "gleam"
args = ["lsp"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls"]
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "gleam"
auto-format = true
formatter = { command = "gleam", args = ["format", "--stdin"] }
language-servers = ["gleam"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "css"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "lua"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "bash"
indent = { tab-width = 2, unit = "  " }
